name: Qt Test CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mesa-common-dev
          sudo apt-get install build-essential 

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.4' 

      - name: Change permission
        run: chmod +x MieSimulatorGUI.pro
        
      - name: Create Build Directory
        run: mkdir -p build
             cd build

      - name: Run qmake
        run: qmake ../MieSimulatorGUI.pro  
             
      - name: Build     
        run: make -j$(nproc)

      - name: Run Tests
        working-directory: ./build/test
        run: |
          chmod +x MieSimulatorGUI_test
          ./MieSimulatorGUI_test
